package org.example.organization

enum class ErrorCodes(val code: Long) {
    ORGANIZATION_NAME_ALREADY_EXISTS(103),
    ORGANIZATION_NOT_FOUND(104),
    ORGANIZATION_ALREADY_EXISTS(105),
    PASSWORD_IS_INCORRECT(106),
    FOLLOW_ALREADY_EXISTS(108),
    ORGANIZATION_PHONE_NUMBER_ALREADY_EXISTS(202),
    FOLLOW_NOT_FOUND(205),
    EMPLOYEE_NOT_FOUND(111),
}

enum class Position {
    ORG_ADMIN,
    ORG_MANAGER,
    ORG_EMPLOYEE
}