package org.example.organization

enum class ErrorCodes(val code: Long) {

    ORGANIZATION_NOT_FOUND(200),
    ORGANIZATION_ALREADY_EXISTS(201),
    ORGANIZATION_NAME_ALREADY_EXISTS(202),
    ORGANIZATION_PHONE_NUMBER_ALREADY_EXISTS(203),

    EMPLOYEE_NOT_FOUND(210),

    FOLLOW_ALREADY_EXISTS(220),
    FOLLOW_NOT_FOUND(221),

    PASSWORD_IS_INCORRECT(230),
}

enum class Position {
    ORG_ADMIN,
    ORG_MANAGER,
    ORG_EMPLOYEE
}