package org.example.task

enum class ErrorCode(val code: Int) {

    ORGANIZATION_NOT_FOUND(401),

    PROJECT_NOT_FOUND(410),
    PROJECT_ALREADY_EXISTS(411),

    BOARD_NOT_FOUND(420),
    BOARD_ALREADY_EXISTS(421),

    TASK_NOT_FOUND(430),
    TASK_ALREADY_EXISTS(431),

    ACCOUNT_ALREADY_ASSIGNED(440),
    ACCOUNT_TASK_NOT_FOUND(441),

    TASK_STATE_NOT_FOUND(450),
    TASK_STATE_ALREADY_EXISTS(451),


    FORBIDDEN_EXCEPTION(460),
    BAD_REQUEST(461)
}

enum class TaskActionType {
    CREATED,
    UPDATED,
    MOVED_FORWARD,
    MOVED_BACKWARD,
    ASSIGNED,
    FILE_UPLOADED,
    FILE_DELETED,
    TASK_ALL_FILES_DELETED,
    UNASSIGNED,
    DELETED
}

enum class MoveDirection {
    FORWARD, BACKWARD
}

