package org.example.task

enum class ErrorCode(val code: Int) {

    ORGANIZATION_DID_NOT_FOUND(101),

    PROJECT_NOT_FOUND(150),
    PROJECT_ALREADY_EXISTS(151),

    BOARD_NOT_FOUND(150),
    BOARD_ALREADY_EXISTS(151),

    TASK_NOT_FOUND(100),
    TASK_ALREADY_EXISTS(101),

    ACCOUNT_ALREADY_ASSIGNED(170),
    ACCOUNT_TASK_NOT_FOUND(171),

    TASK_STATE_NOT_FOUND(180),

    FORBIDDEN_EXCEPTION(190),
}